name: Run CD

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_AUTH }}"

      - name: Setup Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build
        run: docker build -t gcr.io/${{ secrets.PROJECT_ID }}/testagent:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.PROJECT_ID }}/testagent:latest

      - name: Deploy
        run: |-
          gcloud run deploy testagent \
            --project=${{ secrets.PROJECT_ID }} \
            --image=gcr.io/${{ secrets.PROJECT_ID }}/testagent:latest \
            --region=us-central1 \
            --service-account=${{ secrets.SERVICE_ACCOUNT }} \